version: "3.3"
services:
  db_proxy:
    image: 'gcr.io/cloudsql-docker/gce-proxy:1.16'
    restart: always
    command: /cloud_sql_proxy --dir=/cloudsql -instances=${db_project}:${db_region}:${db_instance}=tcp:0.0.0.0:5432
    ports:
      - '127.0.0.1:5432:5432'
  web:
    depends_on:
      - "db_proxy"
    image: 'gitlab/gitlab-ee:${gitlab_version}'
    restart: always
    hostname: "${host_name}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        letsencrypt['enable'] = false
        external_url 'https://${host_name}'
        letsencrypt['contact_emails'] = ['${contact_email}']
        # Disable the built-in Postgres
        postgresql['enable'] = false
        # Fill in the connection details for database.yml
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_host'] = 'db_proxy'
        gitlab_rails['db_port'] = 5432
        gitlab_rails['db_username'] = '${db_username}'
        gitlab_rails['db_password'] = '${db_password}'
        gitlab_rails['monitoring_whitelist'] = ['172.18.0.1/32', '127.0.0.0/8', '35.191.0.0/16', '130.211.0.0/22']
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.sendgrid.net"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "${smtp_user_name}"
        gitlab_rails['smtp_password'] = "${smtp_password}"
        gitlab_rails['smtp_domain'] = "smtp.sendgrid.net"
        gitlab_rails['smtp_authentication'] = "plain"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        # OmniAuth Configuration
        gitlab_rails['omniauth_enabled'] = true
        gitlab_rails['omniauth_external_providers'] = ['saml']
        gitlab_rails['omniauth_allow_single_sign_on'] = ['saml']
        gitlab_rails['omniauth_sync_email_from_provider'] = 'saml'
        gitlab_rails['omniauth_block_auto_created_users'] = false
        gitlab_rails['omniauth_auto_link_ldap_user'] = false
        gitlab_rails['omniauth_sync_profile_from_provider'] = ['saml']
        gitlab_rails['omniauth_sync_profile_attributes'] = ['email']
        gitlab_rails['omniauth_auto_link_saml_user'] = true
        # Uncomment this once you 100% ready to use SSO
        gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'saml'
        gitlab_rails['omniauth_providers'] = [
          {
            'name': 'saml',
            'args': {
              'assertion_consumer_service_url': 'https://${host_name}/users/auth/saml/callback',
              'idp_cert_fingerprint': 'E7:6D:89:2C:50:06:26:FD:99:00:51:00:5E:A2:DB:C4:3E:8B:FC:22',
              'idp_sso_target_url': 'https://accounts.google.com/o/saml2/idp?idpid=C02t2e74p',
              'issuer': 'https://${host_name}',
              'name_identifier_format': 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
              'attribute_statements': { 'email': ['emailAddress'] }
            },
            'label': 'G Suite'
          }
        ]
        ${custom_ruby_code}
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '/opt/gitlab/home/config:/etc/gitlab'
      - '/opt/gitlab/home/logs:/var/log/gitlab'
      - '/opt/gitlab/home/data:/var/opt/gitlab'
      - '/opt/gitlab/home/ssl:/etc/gitlab/ssl'